project:
  type: website
  output-dir: docs
  resources:
    - "assets/*.css"
    - "assets/*.js"
    - "images/logos/*"

freeze: false
lang: fr

website:
  title: "Paul Faye"
  site-url: https://latsouckfaye.github.io
  description: "Docteur en statistique. Construction, validation et industrialisation de modèles prédictifs appliqués au risque en banque de détail."
  navbar: {}

format:
  html:
    theme:
      dark: [darkly, styles-dark.scss]
      light: [cosmo, styles.scss]
    toc: false
    open-graph: true
    twitter-card: true
    email-obfuscation: javascript
    include-after-body: assets/navlang-include.html

editor: visual
